import Head from 'next/head'
import React from "react";
import FileUpload from '../components/FileUpload';

const Home = () => {

    return (
        <div
            className={
                "home  bg-gray-1 h-screen  flex flex-col justify-center items-center"
            }>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={"main flex flex-col justify-center items-center"}>
                <FileUpload />
            </main>
        </div>
    );
}

export default Home;