import { Button } from '@mui/material';
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
      <div className={"home  bg-gray-1 h-screen	"}>
          <Head>
              <title>Create Next App</title>
              <meta name='description' content='Generated by create next app' />
              <link rel='icon' href='/favicon.ico' />
          </Head>

          <main className={"main flex flex-col justify-center items-center"}>
              <Button
                  variant='contained'
                  className='rounded-none	bg-black hover:border-2 hover:bg-black hover:border-solid hover:border-white'>
                  Upload a Video
              </Button>
          </main>
      </div>
  );
}
